name: Selftest

on: [push, pull_request]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os:
                    - macos-12
                    - macos-14
                    - macos-latest
                    - ubuntu-latest
                    - windows-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up the latest alr
            uses: alire-project/setup-alire@v3

          # Find alr's location
          - name: Find alr
            id: find-alr
            run: |
              echo "alr_path=$(dirname $(which alr))" >> $GITHUB_OUTPUT

          - name: Run action
            uses: ./
            with:
              alr_path: ${{ steps.find-alr.outputs.alr_path }}